grumphp:
  tasks:
    phpcs:
      standard: [ ]
      severity: ~
      error_severity: ~
      warning_severity: ~
      tab_width: ~
      report: full
      report_width: ~
      whitelist_patterns: [ ]
      encoding: ~
      ignore_patterns: [ ]
      sniffs: [ ]
      triggered_by: [ php ]
      exclude: [ ]
      show_sniffs_error_path: true
  environment:
    paths:
      - tests
